version: '3'
services:
  app:
    build: .
    container_name: omnifront
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - NODE_ENV=development
