name: CI Pipeline

on:
  push:
    branches:
      - dev  # Executa quando há push na branch dev
      - main  # Executa quando há push na branch main

jobs:
  audit_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci  
      - name: Run npm audit
        run: npm audit --audit-level=high 
      - name: Merge to main
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "rafaelwollace"
          git config --global user.email "rafael.cunha@gmail.com"
          git checkout main  # Certificar-se de que estamos na branch main
          git merge dev      # Faz o merge da dev para main
          git push origin main  # Faz o push para a branch main

  deploy_to_s3:
    needs: audit_dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garantir que todas as branches sejam trazidas
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Atualizar para a versão do Node.js que você deseja usar
      - name: Install dependencies
        run: npm ci  # Instala as dependências do projeto
      - name: Run npm audit
        run: npm audit --audit-level=high  # Falha se houver vulnerabilidades graves
      - name: Build the project
        run: npm run build  # Cria o build da aplicação (Vite gera na pasta dist/)
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
